version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: personal-website
    container_name: personal-website
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:3001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - personal-website-network

networks:
  personal-website-network:

volumes:
  node_modules: